# Generated by Django 4.2.9 on 2024-01-31 12:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_remove_comment_created_at_remove_comment_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='origin',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='articles.articles', verbose_name='Комментируемая статья'),
        ),
    ]
