# Generated by Django 4.2.9 on 2024-01-31 12:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_alter_comment_origin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='origin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='articles.articles', verbose_name='Комментируемая статья'),
        ),
    ]
